import Link from "next/link";
import { createClient } from "@/lib/supabase/server";
import { archiveFormula, createVersion, duplicateFormula, saveVersionItems } from "../actions";

export default async function FormulaDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) return <main className="p-6">Iniciá sesión.</main>;
  const { data: formula } = await supabase.from("formulas").select("id,name,category,status,photo_url,notes,current_version_id,activity_id").eq("id", id).eq("user_id", user.id).single();
  if (!formula) return <main className="p-6">Fórmula no encontrada.</main>;
  const { data: versions } = await supabase.from("formula_versions").select("id,version_number,water_percentage,yield_quantity,notes,created_at").eq("formula_id", id).order("version_number", { ascending: false });
  const current = versions?.find(v => v.id === formula.current_version_id) ?? versions?.[0];
  const { data: items } = current ? await supabase.from("formula_items").select("id,material_id,ingredient_type,quantity,unit,percentage,notes").eq("formula_version_id", current.id).order("id") : { data: [] as any[] };
  const { data: materials } = await supabase.from("materials").select("id,name,default_unit").eq("user_id", user.id).eq("status", "active").order("name");

  return <main className="mx-auto flex min-h-screen w-full max-w-3xl flex-col gap-5 px-4 py-6 pb-24">
    <div className="flex items-start justify-between gap-4"><div><Link href="/formulas" className="text-sm text-neutral-500">← Fórmulas</Link><h1 className="mt-2 text-2xl font-semibold">{formula.name}</h1><p className="text-sm text-neutral-500">{formula.category || "Sin categoría"} · {formula.status === "active" ? "Activa" : "Archivada"}</p></div>{formula.photo_url && <img src={formula.photo_url} alt="" className="h-16 w-16 rounded-xl object-cover" />}</div>
    <section className="rounded-2xl border p-5 dark:border-neutral-800"><div className="flex items-center justify-between"><div><h2 className="font-semibold">Versión actual</h2><p className="text-sm text-neutral-500">v{current?.version_number ?? 1} · rendimiento {current?.yield_quantity ?? 1}{current?.water_percentage != null ? ` · agua ${current.water_percentage}%` : ""}</p></div><div className="flex gap-2"><form action={duplicateFormula}><input type="hidden" name="formula_id" value={id}/><button className="rounded-lg border px-3 py-2 text-sm">Duplicar</button></form>{formula.status === "active" && <form action={archiveFormula}><input type="hidden" name="formula_id" value={id}/><button className="rounded-lg border px-3 py-2 text-sm">Archivar</button></form>}</div></div>
      <form action={saveVersionItems} className="mt-5 space-y-3"><input type="hidden" name="formula_id" value={id}/><input type="hidden" name="version_id" value={current?.id ?? ""}/><input type="hidden" name="item_count" value={items?.length ?? 0}/>{(items ?? []).map((item, i) => <div key={item.id} className="grid grid-cols-4 gap-2"><select name={`ingredient_type_${i}`} defaultValue={item.ingredient_type} className="rounded-lg border px-2 py-2 text-sm"><option value="material">Material</option><option value="water">Agua</option><option value="additive">Aditivo</option><option value="pigment">Pigmento</option><option value="hardener">Endurecedor</option><option value="other">Otro</option></select><select name={`material_id_${i}`} defaultValue={item.material_id ?? ""} className="rounded-lg border px-2 py-2 text-sm"><option value="">Sin material</option>{(materials ?? []).map(m => <option key={m.id} value={m.id}>{m.name}</option>)}</select><input name={`quantity_${i}`} type="number" step="0.01" defaultValue={item.quantity} className="rounded-lg border px-2 py-2 text-sm"/><input name={`unit_${i}`} defaultValue={item.unit} className="rounded-lg border px-2 py-2 text-sm"/></div>)}{!items?.length && <p className="text-sm text-neutral-500">Todavía no hay ingredientes en esta versión. Podés agregar ingredientes en la próxima edición.</p>}{items?.length ? <button className="rounded-xl bg-neutral-900 px-4 py-2 text-sm font-medium text-white">Guardar ingredientes</button> : null}</form>
    </section>
    <section className="rounded-2xl border p-5 dark:border-neutral-800"><h2 className="font-semibold">Crear nueva versión</h2><p className="mt-1 text-sm text-neutral-500">Editar una fórmula crea una versión nueva; las anteriores quedan intactas.</p><form action={createVersion} className="mt-4 grid gap-3"><input type="hidden" name="formula_id" value={id}/><div className="grid grid-cols-2 gap-3"><label className="text-sm">Rendimiento<input name="yield_quantity" type="number" min="0.01" step="0.01" defaultValue={current?.yield_quantity ?? 1} className="mt-1 w-full rounded-lg border px-3 py-2"/></label><label className="text-sm">Agua (%)<input name="water_percentage" type="number" min="0" step="0.1" defaultValue={current?.water_percentage ?? ""} className="mt-1 w-full rounded-lg border px-3 py-2"/></label></div><textarea name="notes" defaultValue={current?.notes ?? ""} rows={2} placeholder="Notas de esta versión" className="rounded-lg border px-3 py-2"/><button className="rounded-xl bg-neutral-900 px-4 py-2 text-sm font-medium text-white">Crear versión nueva</button></form></section>
    <section><h2 className="mb-2 font-semibold">Historial de versiones</h2><div className="grid gap-2">{(versions ?? []).map(v => <div key={v.id} className={`rounded-xl border p-3 text-sm ${v.id === current?.id ? "border-neutral-900" : ""}`}><b>v{v.version_number}</b> · rendimiento {v.yield_quantity}{v.water_percentage != null ? ` · agua ${v.water_percentage}%` : ""} {v.id === formula.current_version_id ? "· actual" : ""}</div>)}</div></section>
  </main>;
}
